version: "3.9"

services:
  veritabani:
    image: mysql:5.7
    restart: always
    volumes:
      - verilerim:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: veritabani
      MYSQL_USER: kullanici
      MYSQL_PASSWORD: sifre

  
  
  volumes:
    verilerim:



networks:


  